version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root_
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: laravel-phpmyadmin
    restart: always
    ports:
    - 8080:80
    environment:
        PMA_USER: ${DB_USERNAME}
        PMA_PASSWORD: ${DB_PASSWORD}

