version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    env_file: ./app/.env 
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - db_network

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_server
    ports:
     - "8088:80"
    volumes: 
     - ./app:/var/www/html
     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - app
     - db
    networks:
      - db_network
 
  db:
    image: mysql:latest
    container_name: laravel-db
    restart: unless-stopped
    tty: true 
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: forum_database
      MYSQL_ROOT_PASSWORD: root_
    # command: ["--init-file=/docker-entrypoint-initdb.d/init.sql"]
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin
    container_name: laravel-phpmyadmin
    restart: always
    ports:
    - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: user
    networks:
     - db_network


networks:
  db_network:
    driver: bridge
